const data = [
  {
    id: '246016548',
    name: 'Навигационная система Soundmax',
    category: 'Техника для дома',
    units: 'шт',
    amount: '5',
    price: '100',
    total: '500',
  },
  {
    id: '937295527',
    name: 'Настольная игра “На 4-х ногах”',
    category: 'Настольные игры',
    units: 'шт',
    amount: '12',
    price: '14',
    total: '168',
  },
  {
    id: '246016548',
    name: 'Навигационная система Soundmax',
    category: 'Техника для дома',
    units: 'шт',
    amount: '5',
    price: '100',
    total: '500',
  },
  {
    id: '246016548',
    name: 'Навигационная система Soundmax',
    category: 'Техника для дома',
    units: 'шт',
    amount: '5',
    price: '100',
    total: '500',
  },
  {
    id: '246016548',
    name: 'Навигационная система Soundmax',
    category: 'Техника для дома',
    units: 'шт',
    amount: '5',
    price: '100',
    total: '500',
  },
  {
    id: '937295527',
    name: 'Настольная игра “На 4-х ногах”',
    category: 'Настольные игры',
    units: 'шт',
    amount: '12',
    price: '14',
    total: '168',
  },
  {
    id: '246016548',
    name: 'Навигационная система Soundmax',
    category: 'Техника для дома',
    units: 'шт',
    amount: '5',
    price: '100',
    total: '500',
  },
  {
    id: '246016548',
    name: 'Навигационная система Soundmax',
    category: 'Техника для дома',
    units: 'шт',
    amount: '5',
    price: '100',
    total: '500',
  },
];

export {
  data,
};
